###
POST http://localhost:8082/api/v1/charging/auth
Content-Type: application/json

{
  "station_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "driver_id": "long-enough-innit",
  "callback_url": "string"
}