/**
* Charging Authorization API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package at.fcordt.cpauth.apis

import at.fcordt.cpauth.Paths
import at.fcordt.cpauth.models.AuthRequest
import at.fcordt.cpauth.models.AuthResponse
import io.ktor.http.*
import io.ktor.server.request.*
import io.ktor.server.resources.post
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.DefaultApi() {
    val empty = mutableMapOf<String, Any?>()

    post<Paths.chargingAuthRequestPost> {
        val authRequest = call.receive<AuthRequest>()
        //insert into queue todo
        val response = AuthResponse(AuthResponse.Status.accepted, "Request is being processed asynchronously. The result will be sent to the provided callback URL.")
        call.respond(HttpStatusCode.OK,  response);
    }

}
