/**
* Charging Authorization API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package at.fcordt.cpauth.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * 
 * @param stationId 
 * @param driverId 
 * @param callbackUrl This URL will be called when the authorization process is completed. No URL checking as per requirements.
 */
@Serializable
data class AuthRequest(
    @Serializable(with = UUIDSerializer::class)
    @SerialName("station_id")
    val stationId: UUID? = null,
    @SerialName("driver_id")
    val driverId: String? = null,
    /* This URL will be called when the authorization process is completed. No URL checking as per requirements. */
    @SerialName("callback_url")
    val callbackUrl: String? = null
)

