/**
* Charging Authorization API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package at.fcordt.cpauth.models


import kotlinx.serialization.Serializable
/**
 * 
 * @param status 
 * @param message 
 */
@Serializable
data class AuthResponse(
    val status: Status? = null,
    val message: String? = null
)
{
    /**
    * 
    * Values: accepted,denied
    */
    enum class Status(val value: String){
        accepted("accepted"),
        denied("denied");
    }
}

