/**
* Charging Authorization API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package at.fcordt.cpauth

import io.ktor.resources.*
import kotlinx.serialization.*
import at.fcordt.cpauth.models.*
import io.ktor.server.routing.*

object Paths {
    /**
     * Asynchronous auth request
     * 
     * @param authRequest  (optional)
     */
    @Resource("/api/v1/charging/auth") class chargingAuthRequestPost()

}
